#!/bin/bash

set -e

die() {
    echo "$*" 1>&2
    exit 1
}
dieget() {
    echo "$1: missing repository"
    echo "hg clone http://bragi.nvidia.com/~tmb/$1"
    exit 2
}

pipx() {
    echo
    echo "################ pip3 $* ################"
    echo
    pip3 "$@"
}

type pip3 || die "install pip3"
python3 -m virtualenv --version || die "install virtualenv for python3"

test -d venv || python3 -m virtualenv venv

source venv/bin/activate

pipx install virtualenv
pipx install numpy
#pipx install scipy
#pipx install scikit-image
#pipx install scikit-learn

pipx install future
pipx install six
pipx install braceexpand
pipx install imageio
pipx install Pillow
pipx install simplejson
pipx install msgpack

pipx install matplotlib
pipx install ipython
pipx install jupyter
#pipx install bash_kernel
#pipx install sos
#pipx install sos-notebook
#pipx install sos-python
#pipx install sos-bash

pipx install torch
pipx install torchvision

#pipx install tensorflow-gpu
#pipx install keras

pipx install git+git://github.com/NVlabs/torchtrainers.git
pipx install git+git://github.com/NVlabs/webloader.git

echo
echo activate with:
echo source ./venv/bin/activate
echo
